# COLORS---------------------------------
BLUE = (0, 0, 255)
LIGHT_BLUE = (173, 216, 230)
SKY_BLUE = (135, 206, 235)
DEEP_SKY_BLUE = (0, 191, 255)
DODGER_BLUE = (30, 144, 255)
ROYAL_BLUE = (65, 105, 225)
NAVY = (0, 0, 128)
MIDNIGHT_BLUE = (25, 25, 112)
TEAL = (0, 128, 128)
AQUA = (0, 255, 255)
TURQUOISE = (64, 224, 208)
CYAN = (0, 255, 255)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)
LIGHT_GRAY = (192, 192, 192)
SILVER = (192, 192, 192)
CHARCOAL = (54, 69, 79)
GOLD = (255, 215, 0)
BRONZE = (205, 127, 50)
COPPER = (184, 115, 51)
GREEN = (0, 255, 0)
LIME_GREEN = (50, 205, 50)
FOREST_GREEN = (34, 139, 34)
DARK_GREEN = (0, 100, 0)
SPRING_GREEN = (0, 255, 127)
SEA_GREEN = (46, 139, 87)
OLIVE = (128, 128, 0)
PINK = (255, 192, 203)
HOT_PINK = (255, 105, 180)
DEEP_PINK = (255, 20, 147)
LIGHT_PINK = (255, 182, 193)
PLUM = (221, 160, 221)
ORCHID = (218, 112, 214)
MAGENTA = (255, 0, 255)
PURPLE = (128, 0, 128)
VIOLET = (238, 130, 238)
INDIGO = (75, 0, 130)
LAVENDER = (230, 230, 250)
DARK_RED = (139, 0, 0)
RED = (255, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)
DARK_ORANGE = (255, 140, 0)
LIGHT_ORANGE = (255, 200, 100)
SALMON = (250, 128, 114)
DARK_SALMON = (233, 150, 122)
LIGHT_SALMON = (255, 160, 122)
CORAL = (255, 127, 80)
TOMATO = (255, 99, 71)
GOLD = (255, 215, 0)
KHAKI = (240, 230, 140)
BROWN = (139, 69, 19)
SADDLE_BROWN = (139, 69, 19)
PERU = (205, 133, 63)
CHOCOLATE = (210, 105, 30)
BLACK = (0, 0, 0)
NEON_GREEN = (57, 255, 20)
ELECTRIC_BLUE = (125, 249, 255)
NEON_PINK = (255, 20, 147)
LASER_RED = (255, 36, 0)
BRIGHT_PURPLE = (191, 64, 191)

# ASTEROIDS------------------------------
ASTEROID_BOUNCINESS = 1.0
ASTEROID_DRAG = 0.5
ASTEROID_MIN_RADIUS = 18
ASTEROID_KINDS = 4
ASTEROID_MAX_ANGULAR_VELOCITY = 135
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPEED = 195
ASTEROID_MIN_ANGULAR_VELOCITY = 45
ASTEROID_MIN_SPEED = 90
ASTEROID_SPAWN_RATE_SECONDS = 1.2
ASTEROID_SPLIT_ACCELERATION = 2.1
ASTEROID_SPLIT_FACTOR_MIN = 0.3
ASTEROID_WEIGHT = 8

# MENUS/GAME_STATES----------------------
GAME_OVER = "game_over"
GAME_RUNNING = "game_running"
PAUSED = "paused"
MAIN_MENU = "main_menu"

# PLAYER---------------------------------
PLAYER_COLLISION_ASTEROID_TRANSFER = 0.85
PLAYER_COLLISION_PLAYER_DAMPING = 0.30
PLAYER_ACCELERATION_RATE = 250
PLAYER_BLINK_TIMER = 0.2
PLAYER_BOUNCINESS = 1.0
PLAYER_BRAKE_SPEED = 350
PLAYER_COLLISION_IMPACT_SCALE = 1.0
PLAYER_DRAG = 35
PLAYER_FORWARD_DECELERATION_RATE = 40
PLAYER_PERPENDICULAR_DECELERATION_RATE = 180
PLAYER_PERPENDICULAR_BRAKE_SPEED = 260
PLAYER_IMPACT_DRAG = 250
PLAYER_RADIUS = 20
PLAYER_DAMAGE_COOLDOWN_SECONDS = 3
PLAYER_STRAFE_SPEED = 225
PLAYER_MAX_SPEED = 450
PLAYER_TURN_SPEED = 300
PLAYER_WEIGHT = 1
LIFE_LOSS_SCORE = -50
GAME_OVER_SCORE = -500

# PROJECTILES----------------------------
PROJECTILE_BOUNCINESS = 0
PROJECTILE_COLOR = WHITE
PROJECTILE_DAMAGE = 1
PROJECTILE_RADIUS = 2
PROJECTILE_WEIGHT = 1
PROJECTILE_DRAG = 0
# ----KINETIC_PROJECTILE-----------------
KINETIC_PROJECTILE_BOUNCINESS = 0
KINETIC_PROJECTILE_COLOR = SILVER
KINETIC_PROJECTILE_DAMAGE = 3
KINETIC_PROJECTILE_DRAG = 0
KINETIC_PROJECTILE_COLLISION_IMPACT_SCALE = 1.75
KINETIC_PROJECTILE_RADIUS = 2
KINETIC_PROJECTILE_WEIGHT = 1
# ----PLASMA_PROJECTILE------------------
PLASMA_PROJECTILE_BOUNCINESS = 0
PLASMA_PROJECTILE_COLOR = MAGENTA
PLASMA_PROJECTILE_DAMAGE = 16
PLASMA_PROJECTILE_DRAG = 0
PLASMA_PROJECTILE_RADIUS = 6
PLASMA_PROJECTILE_WEIGHT = 1
# ----ROCKET_PROJECTILE------------------
ROCKET_PROJECTILE_BOUNCINESS = 0
ROCKET_PROJECTILE_COLOR = ORANGE
ROCKET_PROJECTILE_DAMAGE = 50
ROCKET_PROJECTILE_DRAG = 0.5
ROCKET_PROJECTILE_RADIUS = 4
ROCKET_PROJECTILE_SPEED = 500
ROCKET_PROJECTILE_WEIGHT = 2

# DRONES---------------------------------
DRONE_BOUNCINESS = 1.0
DRONE_DRAG = 0
DRONE_LINE_WIDTH = 5
DRONE_ORBIT_ANGLE_OFFSET = 0
DRONE_ORBIT_RADIUS = 55
DRONE_ORBIT_SPEED = 120
DRONE_RADIUS = 14
DRONE_PROJECTILE_SPEED = 600
DRONE_WEAPONS_FREE_TIMER = 0.4
DRONE_TURN_SPEED = 450
DRONE_WEIGHT = 1
# ----EXPLOSIVE_DRONE--------------------
EXPLOSIVE_DRONE_BODY_COLOR = ELECTRIC_BLUE
EXPLOSIVE_DRONE_WEAPONS_PLATFORM_COLOR = CORAL
EXPLOSIVE_DRONE_WEAPONS_RANGE = 340
EXPLOSIVE_DRONE_WEAPONS_FREE_TIMER = 1.4
EXPLOSIVE_DRONE_PROJECTILE_SPEED = ROCKET_PROJECTILE_SPEED
EXPLOSIVE_DRONE_LAUNCHER_RADIUS = 6
EXPLOSIVE_DRONE_DOOR_OFFSET = 3
EXPLOSIVE_DRONE_DOOR_WIDTH = 3
EXPLOSIVE_DRONE_DOOR_LENGTH = 8
EXPLOSIVE_DRONE_DOOR_ANIMATION_TIME = 0.18
# ----KINETIC_DRONE----------------------
KINETIC_DRONE_BODY_COLOR = CHOCOLATE
KINETIC_DRONE_WEAPONS_PLATFORM_COLOR = SILVER
KINETIC_DRONE_WEAPONS_RANGE = 260
KINETIC_DRONE_WEAPONS_FREE_TIMER = 0.12
KINETIC_DRONE_PROJECTILE_SPEED = 1100
KINETIC_DRONE_WEAPONS_PLATFORM_LENGTH = 10
KINETIC_DRONE_WEAPONS_PLATFORM_FRONT_WIDTH = 4
KINETIC_DRONE_WEAPONS_PLATFORM_BACK_WIDTH = 8
# ----LASER_DRONE------------------------
LASER_DRONE_BODY_COLOR = SALMON
LASER_DRONE_DAMAGE = 100
LASER_DRONE_WEAPONS_RANGE = 420
LASER_DRONE_WEAPONS_FREE_TIMER = 2.5
LASER_DRONE_WEAPONS_PLATFORM_LENGTH = 10
LASER_DRONE_WEAPONS_PLATFORM_WIDTH = 10
LASER_DRONE_WEAPONS_PLATFORM_OFFSET = 4
# ----PLASMA_DRONE-----------------------
PLASMA_DRONE_BODY_COLOR = FOREST_GREEN
PLASMA_DRONE_PROJECTILE_SPEED = 750
PLASMA_DRONE_WEAPONS_FREE_TIMER = 0.8
PLASMA_DRONE_WEAPONS_PLATFORM_COLOR = MAGENTA
PLASMA_DRONE_WEAPONS_PLATFORM_LENGTH_OFFSET = 2
PLASMA_DRONE_WEAPONS_PLATFORM_WIDTH = 7
PLASMA_DRONE_WEAPONS_RANGE = 750
# ----SENTINEL_DRONE----------------------
SENTINEL_DRONE_BODY_COLOR = GOLD
SENTINEL_DRONE_SHIELD_CREATE_TIMER = 4
SENTINEL_DRONE_SHIELD_REPAIR_TIMER = 1.2
SENTINEL_DRONE_WEAPONS_PLATFORM_COLOR = CYAN

# GAMEPLAY_EFFECTS-----------------------
# ----AREA_OF_EFFECT---------------------
# --------ROCKET_HIT---------------------
ROCKET_HIT_RADIUS = 70
ROCKET_HIT_DAMAGE = 12
# ----SINGLE_TARGET_EFFECT---------------
# --------OVERKILL-----------------------
OVERKILL_CHILD_SIZE_REDUCTION = 1
OVERKILL_CHILD_COUNT_REDUCTION = 1
OVERKILL_DURATION = 0.01
# --------PLASMA_BURN--------------------
PLASMA_BURN_DAMAGE = 3
PLASMA_BURN_TICK_RATE = 0.5
PLASMA_BURN_DURATION = 1.6

# SHIELD---------------------------------
SHIELD_BOUNCINESS = 1.0
SHIELD_COLLISION_IMPACT_SCALE = 1.0
SHIELD_COLOR = AQUA
SHIELD_COLOR_ALPHA = 40
SHIELD_DAMAGE = 25
SHIELD_DRAG = 0
SHIELD_LINE_WIDTH = 3
SHIELD_MAX_HEALTH = 10
SHIELD_WEIGHT = 1

# SCREEN---------------------------------
BASE_SCORE = 50
HEALTH_BAR_HEIGHT = 10
LINE_WIDTH = 2
MENU_BUTTON_HEIGHT = 10
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TOP = 0
SCREEN_LEFT = 0

# VISUAL_EFFECTS-------------------------
EFFECT_DURATION = 0.2
# ----BASE_EXPLOSION---------------------
BASE_EXPLOSION_COLOR = ORANGE
BASE_EXPLOSION_DURATION = 0.16
BASE_EXPLOSION_MAX_ALPHA = 170
# --------ASTEROID_KILL_OVERLAY----------
ASTEROID_KILL_EXPLOSION_COLOR = BRONZE
ASTEROID_KILL_EXPLOSION_DURATION = 0.12
ASTEROID_KILL_EXPLOSION_MAX_ALPHA = 95
# --------OVERKILL_OVERLAY---------------
OVERKILL_EXPLOSION_COLOR = ELECTRIC_BLUE
OVERKILL_EXPLOSION_DURATION = 0.16
OVERKILL_EXPLOSION_MAX_ALPHA = 85
# --------ROCKET_HIT_OVERLAY-------------
ROCKET_HIT_EXPLOSION_COLOR = YELLOW
ROCKET_HIT_EXPLOSION_DURATION = 0.15
ROCKET_HIT_EXPLOSION_MAX_ALPHA = 90
# ----LASER_BEAM-------------------------
LASER_BEAM_COLOR = LASER_RED
LASER_BEAM_WIDTH = 3
LASER_BEAM_DURATION = 0.12
# ----PLASMA_BURN------------------------
PLASMA_BURN_FLASH_DURATION = 0.12
